### ISSUE TITLE
Streaming Real-time Recognition WebSocket Server: FAILED!!

### ISSUE THREAD

**Issue by maobon** [0x5446/api4sensevoice#8]
(api4sensevoice-main) PS D:\workspace-python\api4sensevoice-main> python server_wss.py --port 8888
DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\xin\.conda\envs\api4sensevoice-main\Lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
DEBUG:torio._extension.utils:Loading FFmpeg5
DEBUG:torio._extension.utils:Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\xin\.conda\envs\api4sensevoice-main\Lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
DEBUG:torio._extension.utils:Loading FFmpeg4
DEBUG:torio._extension.utils:Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\xin\.conda\envs\api4sensevoice-main\Lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
DEBUG:torio._extension.utils:Loading FFmpeg
DEBUG:torio._extension.utils:Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\torio\_extension\utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
INFO:root:new registry table has been added: preprocessor_classes
INFO:root:new registry table has been added: adaptor_classes
INFO:root:new registry table has been added: lid_predictor_classes
INFO:datasets:PyTorch version 2.3.0 available.
Traceback (most recent call last):
  File "D:\workspace-python\api4sensevoice-main\server_wss.py", line 19, in <module>
    from modelscope.pipelines import pipeline
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
    from .base import Pipeline
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\modelscope\pipelines\base.py", line 16, in <module>
    from modelscope.msdatasets import MsDataset
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\modelscope\msdatasets\__init__.py", line 2, in <module>
    from modelscope.msdatasets.ms_dataset import MsDataset
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\modelscope\msdatasets\ms_dataset.py", line 24, in <module>
    from modelscope.msdatasets.utils.hf_datasets_util import load_dataset_with_ctx
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\modelscope\msdatasets\utils\hf_datasets_util.py", line 63, in <module>
    from modelscope.msdatasets.utils.hf_file_utils import get_from_cache_ms
  File "C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\modelscope\msdatasets\utils\hf_file_utils.py", line 18, in <module>
    from datasets.utils.file_utils import hash_url_to_filename, get_authentication_headers_for_url, ftp_head, fsspec_head, \
ImportError: cannot import name 'ftp_head' from 'datasets.utils.file_utils' (C:\Users\xin\.conda\envs\api4sensevoice-main\lib\site-packages\datasets\utils\file_utils.py)
(api4sensevoice-main) PS D:\workspace-python\api4sensevoice-main>

**Comment by jxyk2007** [comment]
用这个版本：pip install datasets==2.16.0
